### PR TITLE
upgrade mongoose version

### PR DESCRIPTION
**Pull request by gabx**
Need to upgrade mongoose to 4.6.1 to upgrade democracyOS app

### CODE REVIEW

**Comment by gvilarino** [comment]
Thanks @gabx - We're gonna have to try this out with some of our mode complex data models, since this is used by all our other apps/repos (@mjlescano will help out here).

Also, we don't accept non-pinned versions on our prod dependencies; care to undo that last commit?

Cheers.

**Comment by gabx** [comment]
Please tell me which commit I must undo, it is not clear to me.

**Comment by gvilarino** [comment]
@gabx that'd be: d829a4ee0195e2cedc25934c53f251b33b7c0976 - Just remove the `^` and leave it pinned.

**Comment by gabx** [comment]
@gvilarino done (I hope so)

**Comment by gvilarino** [comment]
That's great! I'll perform some tests with datasets and integrate

**Comment by mjlescano** [comment]
Ok, this is super old, closing.

**Pull request closed without merging**
